// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: png2rm.proto

package png2rm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadPNGRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*UploadPNGRequest_Filename
	//	*UploadPNGRequest_DataChunck
	Data isUploadPNGRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadPNGRequest) Reset() {
	*x = UploadPNGRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_png2rm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPNGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPNGRequest) ProtoMessage() {}

func (x *UploadPNGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_png2rm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPNGRequest.ProtoReflect.Descriptor instead.
func (*UploadPNGRequest) Descriptor() ([]byte, []int) {
	return file_png2rm_proto_rawDescGZIP(), []int{0}
}

func (m *UploadPNGRequest) GetData() isUploadPNGRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadPNGRequest) GetFilename() string {
	if x, ok := x.GetData().(*UploadPNGRequest_Filename); ok {
		return x.Filename
	}
	return ""
}

func (x *UploadPNGRequest) GetDataChunck() []byte {
	if x, ok := x.GetData().(*UploadPNGRequest_DataChunck); ok {
		return x.DataChunck
	}
	return nil
}

type isUploadPNGRequest_Data interface {
	isUploadPNGRequest_Data()
}

type UploadPNGRequest_Filename struct {
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3,oneof"`
}

type UploadPNGRequest_DataChunck struct {
	DataChunck []byte `protobuf:"bytes,2,opt,name=data_chunck,json=dataChunck,proto3,oneof"`
}

func (*UploadPNGRequest_Filename) isUploadPNGRequest_Data() {}

func (*UploadPNGRequest_DataChunck) isUploadPNGRequest_Data() {}

type UploadPNGResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*UploadPNGResponse_Docname
	//	*UploadPNGResponse_DataChunck
	Data isUploadPNGResponse_Data `protobuf_oneof:"data"`
}

func (x *UploadPNGResponse) Reset() {
	*x = UploadPNGResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_png2rm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadPNGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPNGResponse) ProtoMessage() {}

func (x *UploadPNGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_png2rm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPNGResponse.ProtoReflect.Descriptor instead.
func (*UploadPNGResponse) Descriptor() ([]byte, []int) {
	return file_png2rm_proto_rawDescGZIP(), []int{1}
}

func (m *UploadPNGResponse) GetData() isUploadPNGResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadPNGResponse) GetDocname() string {
	if x, ok := x.GetData().(*UploadPNGResponse_Docname); ok {
		return x.Docname
	}
	return ""
}

func (x *UploadPNGResponse) GetDataChunck() []byte {
	if x, ok := x.GetData().(*UploadPNGResponse_DataChunck); ok {
		return x.DataChunck
	}
	return nil
}

type isUploadPNGResponse_Data interface {
	isUploadPNGResponse_Data()
}

type UploadPNGResponse_Docname struct {
	Docname string `protobuf:"bytes,1,opt,name=docname,proto3,oneof"`
}

type UploadPNGResponse_DataChunck struct {
	DataChunck []byte `protobuf:"bytes,2,opt,name=data_chunck,json=dataChunck,proto3,oneof"`
}

func (*UploadPNGResponse_Docname) isUploadPNGResponse_Data() {}

func (*UploadPNGResponse_DataChunck) isUploadPNGResponse_Data() {}

var File_png2rm_proto protoreflect.FileDescriptor

var file_png2rm_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6e, 0x67, 0x32, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x6e, 0x67, 0x32, 0x72, 0x6d, 0x22, 0x5b, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x50, 0x4e, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x63, 0x68, 0x75, 0x6e, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x43, 0x68, 0x75, 0x6e, 0x63, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x5a, 0x0a, 0x11, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x4e, 0x47,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x6f, 0x63, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x6f, 0x63,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0b, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x68, 0x75,
	0x6e, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x61, 0x74,
	0x61, 0x43, 0x68, 0x75, 0x6e, 0x63, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x5e, 0x0a, 0x0d, 0x50, 0x4e, 0x47, 0x32, 0x52, 0x6d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4d, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x6e, 0x67, 0x32, 0x72, 0x6d, 0x2e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x50, 0x4e, 0x47, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x6e, 0x67, 0x32, 0x72, 0x6d, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x50, 0x4e,
	0x47, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x09, 0x5a, 0x07, 0x70, 0x6e, 0x67, 0x32, 0x72, 0x6d, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_png2rm_proto_rawDescOnce sync.Once
	file_png2rm_proto_rawDescData = file_png2rm_proto_rawDesc
)

func file_png2rm_proto_rawDescGZIP() []byte {
	file_png2rm_proto_rawDescOnce.Do(func() {
		file_png2rm_proto_rawDescData = protoimpl.X.CompressGZIP(file_png2rm_proto_rawDescData)
	})
	return file_png2rm_proto_rawDescData
}

var file_png2rm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_png2rm_proto_goTypes = []interface{}{
	(*UploadPNGRequest)(nil),  // 0: png2rm.UploadPNGRequest
	(*UploadPNGResponse)(nil), // 1: png2rm.UploadPNGResponse
}
var file_png2rm_proto_depIdxs = []int32{
	0, // 0: png2rm.PNG2RmService.UploadAndConvert:input_type -> png2rm.UploadPNGRequest
	1, // 1: png2rm.PNG2RmService.UploadAndConvert:output_type -> png2rm.UploadPNGResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_png2rm_proto_init() }
func file_png2rm_proto_init() {
	if File_png2rm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_png2rm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPNGRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_png2rm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadPNGResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_png2rm_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*UploadPNGRequest_Filename)(nil),
		(*UploadPNGRequest_DataChunck)(nil),
	}
	file_png2rm_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*UploadPNGResponse_Docname)(nil),
		(*UploadPNGResponse_DataChunck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_png2rm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_png2rm_proto_goTypes,
		DependencyIndexes: file_png2rm_proto_depIdxs,
		MessageInfos:      file_png2rm_proto_msgTypes,
	}.Build()
	File_png2rm_proto = out.File
	file_png2rm_proto_rawDesc = nil
	file_png2rm_proto_goTypes = nil
	file_png2rm_proto_depIdxs = nil
}
